PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX qb:      <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX pmdds:   <http://publishmydata.com/def/dataset#>   
PREFIX pmdcat:  <http://publishmydata.com/pmdcat#>
# SELECT * 
CONSTRUCT {
    GRAPH ?scheme_metadata_graph {
            
            
            ?record a dcat:CatalogRecord ;
                rdfs:label ?record_lbl ;
                dcterms:issued ?now ;
                dcterms:modified ?now ;
                foaf:primaryTopic ?catalog_id ;
                pmdcat:metadataGraph ?scheme_metadata_graph .
            
            ?cat_entry a pmdcat:Dataset ;
                rdfs:label ?lbl ;
                dcterms:title ?lbl ;
                dcterms:created ?now ;                 
                dcterms:modified ?now ;
                dcterms:issued ?now ;
                pmdcat:graph ?scheme_graph ;
                pmdcat:datasetContents ?scheme .
            
            ?scheme a pmdcat:ConceptScheme .

        ?catalog dcat:record ?record . 
    }
} 
WHERE {
    BIND(<http://gss-data.org.uk/catalog/vocabularies> AS ?catalog)

  ?dim qb:codeList ?scheme .
  GRAPH ?scheme_graph {
      ?scheme rdfs:label ?lbl 
  }
  BIND(IRI(CONCAT(STR(?scheme_graph), "-metadata")) AS ?scheme_metadata_graph)
  BIND( IRI ( REPLACE ( STR(?scheme), "/def/concept-scheme/", "/vocabs/")) AS ?cat_entry)
  BIND( IRI ( CONCAT(STR(?cat_entry), "-catalog-record")) AS ?record)

  BIND( CONCAT(?lbl, " Catalog Record") AS ?record_lbl)
    BIND(NOW() AS ?now)

  BIND(IRI(CONCAT(STR(?scheme), "-metadata")) AS ?scheme__metadata_graph)
  FILTER NOT EXISTS {
    ?cat_entry pmdcat:datasetContents ?scheme .
  }
}