DELETE {
    GRAPH ?g {
        ?s ?p ?scheme 
    }
} 
# SELECT *
WHERE {
    GRAPH ?g {
        BIND(<http://gss-data.org.uk/def/concept-scheme/migration-directions> AS ?scheme)
        # BIND(<http://gss-data.org.uk/def/concept-scheme/price-classification> AS ?scheme)
        ?s ?p ?scheme 
    }
}