PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX qb:      <http://purl.org/linked-data/cube#>

DELETE 
{ 
    GRAPH ?g {
        ?scheme skos:member ?member .
    }
} 
WHERE {
    GRAPH ?g {
        ?scheme a skos:ConceptScheme .
        ?scheme skos:member ?member .
    }
}
