SELECT ?g ?slug_segment (COUNT(?s) AS ?count) {
    GRAPH ?g {
        ?s ?p ?o 
        FILTER(STRSTARTS(STR(?o), "http://reference.data.gov.uk/id/"))
        BIND( STR ( REPLACE ( STR(?o), "http://reference.data.gov.uk/id/", "")) AS ?slug)
        BIND( STRAFTER( ?slug, "/") AS ?last)
        BIND( STR ( REPLACE ( ?slug, ?last, "")) AS ?slug_segment)
    }
}
GROUP BY ?g ?slug_segment
ORDER BY ?g ?slug_segment