PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX qb:      <http://purl.org/linked-data/cube#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX pmdds:   <http://publishmydata.com/def/dataset#>   
PREFIX pmdcat:  <http://publishmydata.com/pmdcat#>

CONSTRUCT {
    GRAPH <http://gss-data.org.uk/graph/components> {
        ?comp_prop ?comp_prop_p ?comp_prop_o
    }
}
# SELECT ?prop_graph ?comp_prop ?comp_prop_p ?comp_prop_o
{
    # BIND(<http://gss-data.org.uk/data/gss_data/trade/ons-uk-trade-in-services> AS ?cube)
    # BIND(<http://gss-data.org.uk/graph/gss_data/trade/ons-uk-trade-in-services> AS ?cube_graph)
    GRAPH ?cube_graph {
            ?cube a qb:DataSet .
            ?cube qb:structure/qb:component ?comp_spec .
            ?comp_spec qb:dimension ?comp_prop .
    }
    
    GRAPH ?prop_graph {
            ?comp_prop ?comp_prop_p ?comp_prop_o .
        }
    
    ?prop_graph <http://publishmydata.com/def/drafter/isPublic> true .
}
GROUP BY ?comp_prop ?comp_prop_p ?comp_prop_o
ORDER BY ?comp_prop 