PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX qb:      <http://purl.org/linked-data/cube#>
PREFIX pmdqb:   <http://publishmydata.com/def/qb/>

SELECT ?comp ?dim ?range ?scheme
{
        
    ?dsd a qb:DataStructureDefinition .
    ?dsd qb:component ?comp .
    ?comp qb:dimension ?dim .
    ?dim rdfs:range ?range .
    ?comp pmdqb:codesUsed ?codesUsedCollection .
    ?codesUsedCollection skos:member ?concept .
    ?concept skos:inScheme ?scheme .
    FILTER NOT EXISTS {
        ?dim qb:codeList ?codelist 
    }
        
}
GROUP BY ?comp ?dim ?scheme ?range
ORDER BY ?dim ?comp 
